CREATE DATABASE e1_web_cursos_db4;

\c e1_web_cursos_db4


CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(30) NOT NULL,
  "password" varchar(30) UNIQUE NOT NULL,
  "age" int
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(100),
  "level" varchar(20) NOT NULL,
  "teacher" varchar(30) NOT NULL,
  "users_id" int
);

CREATE TABLE "courses_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(100) NOT NULL,
  "url" varchar(100) NOT NULL,
  "curso_id" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "curso_id" int
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "users_id" int
);

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "roles" ("users_id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id") REFERENCES "categories" ("curso_id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("curso_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");


INSERT INTO users (name, email, password, age) VALUES 
('Alex', 'Cajas', 'qe123', 26),
('Juan', 'Perez', 'rt852', 35);

INSERT INTO courses (title, description, level, teacher) VALUES 
('marketing', 'curso de marketing en redes sociales', 'principiantes', 'Juan Orozco'),
('programacion', 'curso de node', 'medios', 'Luis Mosquera');

INSERT INTO courses_videos (title, url) VALUES
('Como publicar un reels en instagram', 'www.formacionIG/reels.com'),
('Como crear una base de datos en mysql', 'www.formacionProgramacionSQL.com');

INSERT INTO categories (name) VALUES
('negocios'),
('tecnología');

INSERT INTO roles (name) VALUES
('student'),
('teacher');

\dt 

SELECT * FROM users;

SELECT * FROM courses;

SELECT * FROM courses_videos;

SELECT * FROM categories;

SELECT * FROM roles;
